# dummy release script
#
# DO NOT invoke this from a pgfplots directory, 
# use 
# make -f pgfplots/scripts/pgfplots/Makefile.pgfplots_release_sourceforge
#VERSION=_unstable
DIR=pgfplots
VERSION=_1.6.1

ZIP=pgfplots$(VERSION).tds.zip
CTANZIP=pgfplots$(VERSION).ctan.flatdir.zip
PDF=pgfplots$(VERSION).pdf
TEX_NOTES=$(DIR)/doc/latex/pgfplots/TeX-programming-notes.pdf
PDFTABLE=pgfplotstable$(VERSION).pdf
CHANGELOG=ChangeLog$(VERSION)
README=README$(VERSION)
REVISIONFILE=pgfplots$(VERSION).revision

files: zip ctanzip pdf $(README) $(CHANGELOG)

all: uploaddist download gallery 

zip: $(ZIP)

pdf: $(PDF) $(PDFTABLE)

revisionfile: $(REVISIONFILE)

uploadindexhtml: /tmp/index.html
	scp $< ludewich,pgfplots@web.sourceforge.net:htdocs/
	

upload: $(ZIP) $(PDF) $(PDFTABLE) $(CHANGELOG) $(README) $(REVISIONFILE)
	scp $^ $(TEX_NOTES) ludewich,pgfplots@web.sourceforge.net:htdocs/

uploaddist: $(ZIP) $(PDF) $(PDFTABLE)
	scp $(DIR)/doc/latex/pgfplots/pgfplots.pdf \
		$(DIR)/doc/latex/pgfplots/pgfplotstable.pdf \
		ludewich,pgfplots@web.sourceforge.net:htdocs/

FORCE:

ctanzip: $(CTANZIP)

$(CTANZIP): $(ZIP)
	rm -fr /tmp/pgfplots /tmp/pgfplots.ctan.tmp $@
	mkdir -p /tmp/pgfplots /tmp/pgfplots.ctan.tmp
	cd /tmp/pgfplots.ctan.tmp && unzip $(abspath $(ZIP))
	mv /tmp/pgfplots.ctan.tmp/doc/latex/pgfplots /tmp/pgfplots/doc
	echo "Please search for pgfplots.tds.zip and install that one into a local texmf branch (which is typically simpler). This release is intended to satisfy CTAN package browsing policies." > /tmp/pgfplots/INSTALL
	mv /tmp/pgfplots.ctan.tmp/source/context/third/pgfplots/pgfplotstests.tar.bz2 /tmp/pgfplots.ctan.tmp/pgfplotstests.context.tar.bz2 
	cd /tmp/pgfplots.ctan.tmp && mv doc/plain/pgfplots/pgfplotsexample.tex pgfplotsexample.plaintex.tex
	cd /tmp/pgfplots.ctan.tmp && mv doc/plain/pgfplots/pgfplotsexample.pdf pgfplotsexample.plaintex.pdf
	cd /tmp/pgfplots.ctan.tmp && mv doc/context/third/pgfplots/pgfplotsexample.tex pgfplotsexample.context.tex
	cd /tmp/pgfplots.ctan.tmp && mv doc/context/third/pgfplots/pgfplotsexample.pdf pgfplotsexample.context.pdf
	rm /tmp/pgfplots.ctan.tmp/README
	find /tmp/pgfplots.ctan.tmp -type f -exec cp -i {} /tmp/pgfplots \;
	cd /tmp && zip -r $(abspath $@) pgfplots


$(ZIP): FORCE
	rm -fr /tmp/pgfplots /tmp/$@
	cd $(DIR) && scripts/pgfplots/pgfplotsrevisionfile.sh
	rsync --copy-links \
		--exclude=.git \
		--exclude='.*.sw?' \
		--exclude='*.aux' \
		--exclude='*.log' \
		--exclude='*~' \
		--exclude='*.bbl' \
		--exclude='*.blg' \
		--exclude='*.idx' \
		--exclude='*.ilg' \
		--exclude='*.log' \
		--exclude='*.ind' \
		--exclude='*.toc' \
		--exclude='*.out' \
		--exclude='*.djs' \
		--exclude='*.tmp' \
		--exclude='*.tuo' \
		--exclude='*.tui' \
		--exclude='*.top' \
		--exclude='*.pgf' \
		--exclude='*.mp' \
		--exclude='*.md5' \
		--exclude='.gitignore' \
		--exclude='.cvsignore' \
		--exclude='pgfplotsrevisionfile.sh' \
		--exclude='pgfplots_in_ubuntu.readme.txt' \
		--exclude='pgfplotstable.example1.out.*' \
		--exclude='source/latex/pgfplots/pgfplotstest/unittests/references' \
		--exclude='doc/latex/pgfplots/bugtracker' \
		--exclude='*.diff' \
		--exclude='expensiveexample*' \
		--exclude='Makefile.pgfplots_release_sourceforge' \
		--exclude='pgfplotsDEV_copy_files_from_pgf.sh' \
		-r $(DIR) /tmp
	make -C /tmp/$(DIR)/doc/latex/pgfplots/gallery/ clean
	find /tmp/$(DIR)/source/latex/pgfplots/pgfplotstest \( -name 'unittest*.png' -o -name 'unittest*.pdf' \) -delete
	#cd /tmp/$(DIR)/source/latex/pgfplots/ && zip --move -r pgfplotstests.zip *
	#cd /tmp/$(DIR)/source/context/third/pgfplots/ && zip --move -r pgfplotstests.zip *
	cd /tmp/$(DIR)/source/latex/pgfplots/ && tar cjf pgfplotstests.tar.bz2 --remove-files *
	cd /tmp/$(DIR)/source/context/third/pgfplots/ && tar cjf pgfplotstests.tar.bz2 --remove-files *
	cd /tmp/$(DIR) && zip -r /tmp/$@ *
	cp /tmp/$@ $@
	find `pwd` -maxdepth 1 \( -name '$(@:.zip=)*' \) -ls

$(REVISIONFILE): FORCE
	P=`pwd`; cd $(DIR) && echo "`date +%Y-%m-%d` Revision `git describe --tags HEAD`" >$$P/$@

$(CHANGELOG): FORCE
	cp $(DIR)/doc/latex/pgfplots/ChangeLog $@

$(README): FORCE
	cp $(DIR)/doc/generic/pgfplots/README $@

$(PDF): $(DIR)/doc/latex/pgfplots/pgfplots.pdf
	cp $< $@

$(PDFTABLE): $(DIR)/doc/latex/pgfplots/pgfplotstable.pdf
	cp $< $@

download:
	scp  ludewich,pgfplots@web.sourceforge.net:htdocs/index.html /tmp || exit 1
	echo "index.html copied to /tmp"

gallery:
	echo "Remaking gallery ... "
	#make -C $(DIR)/doc/latex/pgfplots/gallery 
	scp $(DIR)/doc/latex/pgfplots/gallery/gallery.{html,css} $(DIR)/doc/latex/pgfplots/gallery/example*.png $(DIR)/doc/latex/pgfplots/gallery/example*.pdf $(DIR)/doc/latex/pgfplots/gallery/example*.tex ludewich,pgfplots@web.sourceforge.net:htdocs/
