VERSION=1.3

ZIP=pgfplots$(VERSION).tds.zip
PDF=pgfplots$(VERSION).pdf
PDFTABLE=pgfplotstable$(VERSION).pdf

all: upload download gallery 

uploadindexhtml: /tmp/index.html
	scp $< ludewich,pgfplots@web.sourceforge.net:htdocs/
	

upload: $(ZIP) $(PDF) $(PDFTABLE)
	scp $^ ludewich@frs.sourceforge.net:uploads
	scp ~/code/tex/pgfplots/doc/latex/pgfplots/pgfplots.pdf ~/code/tex/pgfplots/doc/latex/pgfplots/pgfplotstable.pdf ludewich,pgfplots@web.sourceforge.net:htdocs/

pgfplots.tds.zip:
	rm -fr /tmp/pgfplots /tmp/$@
	rsync --copy-links \
		--exclude=.git \
		--exclude='.*.sw?' \
		--exclude='*.aux' \
		--exclude='*.log' \
		--exclude='*~' \
		--exclude='*.bbl' \
		--exclude='*.blg' \
		--exclude='*.idx' \
		--exclude='*.ilg' \
		--exclude='*.log' \
		--exclude='*.ind' \
		--exclude='*.toc' \
		--exclude='*.out' \
		--exclude='*.djs' \
		--exclude='*.tmp' \
		--exclude='*.tuo' \
		--exclude='*.tui' \
		--exclude='*.top' \
		--exclude='*.pgf' \
		--exclude='*.mp' \
		--exclude='.gitignore' \
		--exclude='.cvsignore' \
		--exclude='pgfplotstable.example1.out.*' \
		--exclude='expensiveexamplepgfplots*' \
		--exclude='Makefile.pgfplots_release_sourceforge' \
		--exclude='pgfplotsDEV_copy_files_from_pgf.sh' \
		--exclude='potentialauthors.txt' \
		-r pgfplots /tmp
	make -C /tmp/pgfplots/doc/latex/pgfplots/gallery/ clean
	cd /tmp/pgfplots/source/latex/pgfplots/ && zip --move -r pgfplotstests.zip *
	cd /tmp/pgfplots/source/context/third/pgfplots/ && zip --move -r pgfplotstests.zip *
	cd /tmp/pgfplots && zip -r /tmp/$@ *
	cp /tmp/$@ $@
	find `pwd` -maxdepth 1 \( -name '$(@:.zip=)*' \) -ls

$(ZIP): pgfplots.tds.zip
	if [ ! -f $@ ]; then
		cp pgfplots.tds.zip $@ || exit 1
	fi

$(PDF): ~/code/tex/pgfplots/doc/latex/pgfplots/pgfplots.pdf
	cp $< $@

$(PDFTABLE): ~/code/tex/pgfplots/doc/latex/pgfplots/pgfplotstable.pdf
	cp $< $@

download:
	scp  ludewich,pgfplots@web.sourceforge.net:htdocs/index.html /tmp || exit 1
	echo "index.html copied to /tmp"

gallery:
	echo "Remaking gallery ... "
	make -C ~/code/tex/pgfplots/doc/latex/pgfplots/gallery 
	scp ~/code/tex/pgfplots/doc/latex/pgfplots/gallery/example* ludewich,pgfplots@web.sourceforge.net:htdocs/
