name: Manual

on: [push, pull_request]

env:
  TERM: "xterm-256color"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    strategy:
      matrix:
        engine: [lualatex]

    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Fixup Run actions/checkout
      run: git config --global --add safe.directory '*'

    - name: Restore cache for expensiveexamples and gnuplot
      uses: actions/cache/restore@v6
      with:
        path: |
          doc/latex/pgfplots/figures/expensiveexamples
          doc/latex/pgfplots/gnuplot
        key: manual-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: manual

    - name: Build the manual
      run: bash .github/workflows/manual.sh

    - name: Save cache for expensiveexamples and gnuplot
      uses: actions/cache/save@v6
      if: always()
      with:
        path: |
          doc/latex/pgfplots/figures/expensiveexamples
          doc/latex/pgfplots/gnuplot
        key: manual-${{ github.run_id }}-${{ github.run_attempt }}
